---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: my-app
  labels:
    app: mysql
    owner: marcus
    env: development
  annotations:
    kubernetes.io/change-cause: "Initial deployment of mysql database"
spec:
  serviceaccountName: notoken-sa
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: backend
  template:
    metadata:
      labels:
        app: "my-app"
        tier: "backend"
        costcenter: "4711"
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mysqldb-pvc
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-secret
                  key: root_password
            - name: foo
              value: "bar"
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
