---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pvc
  namespace: my-app
spec:
  resources:
    requests:
      storage: 343M
  volumeMode: Filesystem
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteOnce
