name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "README.md"
      - "setup/**.md"
      - "labs/**/*.md"

jobs:
  convert-and-release:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Convert Markdown to PDF
      run: |
        pandoc README.md -o README.pdf --toc

    - name: Create Release Tag
      id: create_tag
      run: |
        # Generate a tag name based on the current date and short commit hash
        TAG_NAME="release-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Generated tag name: $TAG_NAME"

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
        files: pdfs/**/*.pdf

    - name: Convert to HTML
      uses: gbraad-actions/pandoc@main
      with:
        source: "labs/*.md"
        output-format: html
        output-dir: ./html
        extra-args: "--standalone --css=style.css"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages
