name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "README.md"
      - "setup/**.md"
      - "labs/**/*.md"

jobs:
  convert-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-plain-generic fonts-noto

    - name: Convert Markdown to PDF
      run: |
        mkdir -p pdfs
        for md_file in $(find . -name "*.md"); do
          echo "Converting $md_file to PDF..."
          relative_path=$(echo "$md_file" | sed 's|^\./||')
          pdf_dir="pdfs/$(dirname "$relative_path")"
          mkdir -p "$pdf_dir"
          if pandoc "$md_file" -o "${pdf_dir}/$(basename "${md_file%.md}".pdf)" --pdf-engine=xelatex -M emoji=noto-emoji -V mainfont="Noto Serif" -V monofont="Noto Mono" -V geometry:margin=1in; then
            echo "Successfully converted $md_file to PDF"
          else
            echo "Failed to convert $md_file to PDF"
            exit 1
          fi
        done

    - name: Create Release Tag
      id: create_tag
      run: |
        # Generate a tag name based on the current date and short commit hash
        TAG_NAME="release-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Generated tag name: $TAG_NAME"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload PDFs to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pdfs/
        asset_name: markdown-pdfs.zip
        asset_content_type: application/zip

    - name: Convert Markdown to HTML
      run: |
        mkdir -p html
        for md_file in $(find . -name "*.md"); do
          echo "Converting $md_file to HTML..."
          relative_path=$(echo "$md_file" | sed 's|^\./||')
          html_dir="html/$(dirname "$relative_path")"
          mkdir -p "$html_dir"
          if pandoc "$md_file" -o "${html_dir}/$(basename "${md_file%.md}".html)" --standalone; then
            echo "Successfully converted $md_file to HTML"
          else
            echo "Failed to convert $md_file to HTML"
            exit 1
          fi
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        publish_branch: gh-pages
