name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "README.md"
      - "setup/**.md"
      - "labs/**/*.md"

jobs:
  convert-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

    - name: Convert Markdown to PDF
      run: |
        mkdir -p pdfs
        for md_file in $(find . -name "*.md"); do
          echo "Converting $md_file to PDF..."
          # Remove the leading './' from the md_file path
          relative_path=$(echo "$md_file" | sed 's|^\./||')
          # Create the directory structure for the PDF file
          pdf_dir="pdfs/$(dirname "$relative_path")"
          mkdir -p "$pdf_dir"
          if pandoc "$md_file" -o "${pdf_dir}/$(basename "${md_file%.md}".pdf)"; then
            echo "Successfully converted $md_file"
          else
            echo "Failed to convert $md_file"
            exit 1
          fi
        done
      continue-on-error: false

    - name: Create Release Tag
      id: create_tag
      run: |
        # Generate a tag name based on the current date and short commit hash
        TAG_NAME="release-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Generated tag name: $TAG_NAME"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
        release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload PDFs to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./pdfs/
        asset_name: markdown-pdfs.zip
        asset_content_type: application/zip
