name: Convert Markdown to HTML and Deploy to GitHub Pages
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "README.md"
      - "setup/**.md"
      - "labs/**/*.md"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and install Markdown converter
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          mkdir -p site
          find . -name "*.md" -type f | while read mdfile; do
            relpath="${mdfile#./}"
            htmlpath="site/${relpath%.md}.html"
            mkdir -p "$(dirname "$htmlpath")"
            pandoc "$mdfile" -o "$htmlpath"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
